[project]
name = "mgt60333-quiz-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "logging>=0.4.9.6",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "streamlit>=1.46.1",
]
